



-- Q1: ACTIVE VS INACTIVE DISTRIBUTION BY CITY & OVERALL
-- Relations: FACT → DIM_STATUS, FACT → DIM_CITY

-- Q1a: Segregated by city
SELECT
    C.CITY_NAME,
    S.STATUS_GROUP,
    COUNT(*) AS LICENSE_COUNT
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_STATUS S ON F.STATUS_SK = S.STATUS_SK
JOIN DIM_CITY   C ON F.CITY_SK   = C.CITY_SK
GROUP BY C.CITY_NAME, S.STATUS_GROUP
ORDER BY C.CITY_NAME, S.STATUS_GROUP;

-- Q1b: Aggregated across all cities
SELECT
    S.STATUS_GROUP,
    COUNT(*) AS LICENSE_COUNT
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_STATUS S ON F.STATUS_SK = S.STATUS_SK
GROUP BY S.STATUS_GROUP
ORDER BY S.STATUS_GROUP;


-- Q2: PREDOMINANT INDUSTRIES FOR BUSINESS LICENSES
-- Relations: FACT → DIM_INDUSTRY
SELECT
    I.INDUSTRY_GROUP,
    I.INDUSTRY_LABEL,
    I.LICENSE_TYPE,
    COUNT(*) AS LICENSE_COUNT
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_INDUSTRY I ON F.INDUSTRY_SK = I.INDUSTRY_SK
GROUP BY I.INDUSTRY_GROUP, I.INDUSTRY_LABEL, I.LICENSE_TYPE
ORDER BY LICENSE_COUNT DESC;


-- Q3: TOP 5 GEOGRAPHIC AREAS (BY ZIP CODE & STREET NAME) PER CITY
-- Relations: FACT → DIM_LOCATION, FACT → DIM_CITY


-- Q3a: Top 5 zip codes per city
SELECT *
FROM (
    SELECT
        C.CITY_NAME,
        L.ZIP,
        COUNT(*) AS LICENSE_COUNT,
        ROW_NUMBER() OVER (PARTITION BY C.CITY_NAME ORDER BY COUNT(*) DESC) AS RNK
    FROM FACT_BUSINESS_LICENSE F
    JOIN DIM_LOCATION L ON F.LOCATION_SK = L.LOCATION_SK
    JOIN DIM_CITY     C ON F.CITY_SK     = C.CITY_SK
    GROUP BY C.CITY_NAME, L.ZIP
) RANKED
WHERE RNK <= 5
ORDER BY CITY_NAME, RNK;

-- Q3b: Top 5 street names per city
SELECT *
FROM (
    SELECT
        C.CITY_NAME,
        L.STREET_NAME,
        COUNT(*) AS LICENSE_COUNT,
        ROW_NUMBER() OVER (PARTITION BY C.CITY_NAME ORDER BY COUNT(*) DESC) AS RNK
    FROM FACT_BUSINESS_LICENSE F
    JOIN DIM_LOCATION L ON F.LOCATION_SK = L.LOCATION_SK
    JOIN DIM_CITY     C ON F.CITY_SK     = C.CITY_SK
    GROUP BY C.CITY_NAME, L.STREET_NAME
) RANKED
WHERE RNK <= 5
ORDER BY CITY_NAME, RNK;



-- Q4: TREND IN ISSUANCE OF BUSINESS LICENSES OVER TIME
-- Relations: FACT → DIM_DATE (via ISSUE_DATE_SK)


-- Q4a: Yearly trend
SELECT
    D.YEAR,
    COUNT(*) AS LICENSES_ISSUED
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_DATE D ON F.ISSUE_DATE_SK = D.DATE_SK
GROUP BY D.YEAR
ORDER BY D.YEAR;

-- Q4b: Monthly trend
SELECT
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME,
    COUNT(*) AS LICENSES_ISSUED
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_DATE D ON F.ISSUE_DATE_SK = D.DATE_SK
GROUP BY D.YEAR, D.MONTH, D.MONTH_NAME
ORDER BY D.YEAR, D.MONTH;



-- Q5: TRENDS IN ABANDONMENT OF BUSINESS LICENSES
-- Relations: FACT → DIM_STATUS, FACT → DIM_DATE (via STATUS_CHANGE_DATE_SK)


SELECT
    D.YEAR,
    D.QUARTER,
    S.RAW_STATUS,
    COUNT(*) AS ABANDONED_COUNT
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_STATUS S ON F.STATUS_SK              = S.STATUS_SK
JOIN DIM_DATE   D ON F.STATUS_CHANGE_DATE_SK  = D.DATE_SK
WHERE S.RAW_STATUS IN ('Abandoned', 'Expired', 'Cancelled', 'Revoked')
   OR S.STATUS_GROUP = 'Inactive'
GROUP BY D.YEAR, D.QUARTER, S.RAW_STATUS
ORDER BY D.YEAR, D.QUARTER, ABANDONED_COUNT DESC;


-- Q6: SEASONAL VARIATIONS IN ISSUANCE OF BUSINESS LICENSES
-- Relations: FACT → DIM_DATE (via ISSUE_DATE_SK)

-- Q6a: By month (seasonality)
SELECT
    D.MONTH,
    D.MONTH_NAME,
    COUNT(*) AS LICENSES_ISSUED
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_DATE D ON F.ISSUE_DATE_SK = D.DATE_SK
GROUP BY D.MONTH, D.MONTH_NAME
ORDER BY D.MONTH;

-- Q6b: By quarter
SELECT
    D.QUARTER,
    COUNT(*) AS LICENSES_ISSUED
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_DATE D ON F.ISSUE_DATE_SK = D.DATE_SK
GROUP BY D.QUARTER
ORDER BY D.QUARTER;

-- Q6c: Weekday vs Weekend
SELECT
    D.IS_WEEKEND,
    COUNT(*) AS LICENSES_ISSUED
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_DATE D ON F.ISSUE_DATE_SK = D.DATE_SK
GROUP BY D.IS_WEEKEND
ORDER BY D.IS_WEEKEND;


-- Q7: URGENCY CATEGORY COUNTS ACROSS ALL CITIES
-- Relations: FACT → DIM_CITY (URGENCY is on FACT table)


-- Q7a: Overall urgency distribution
SELECT
    F.URGENCY,
    COUNT(*) AS LICENSE_COUNT
FROM FACT_BUSINESS_LICENSE F
GROUP BY F.URGENCY
ORDER BY
    CASE F.URGENCY
        WHEN 'Immediate' THEN 1
        WHEN 'High'      THEN 2
        WHEN 'Medium'    THEN 3
        WHEN 'Low'       THEN 4
        WHEN 'Unknown'   THEN 5
    END;

-- Q7b: Urgency distribution by city
SELECT
    C.CITY_NAME,
    F.URGENCY,
    COUNT(*) AS LICENSE_COUNT
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_CITY C ON F.CITY_SK = C.CITY_SK
GROUP BY C.CITY_NAME, F.URGENCY
ORDER BY C.CITY_NAME,
    CASE F.URGENCY
        WHEN 'Immediate' THEN 1
        WHEN 'High'      THEN 2
        WHEN 'Medium'    THEN 3
        WHEN 'Low'       THEN 4
        WHEN 'Unknown'   THEN 5
    END;


-- Q8: INACTIVE BUSINESSES WITH CONTACT DETAILS FOR RENEWAL REMINDERS
-- Relations: FACT → DIM_STATUS, FACT → DIM_BUSINESS, FACT → DIM_CITY

SELECT
    C.CITY_NAME,
    B.LEGAL_NAME,
    B.DBA_NAME,
    B.CONTACT_PHONE,
    B.CONTACT_EMAIL,
    S.RAW_STATUS,
    S.STATUS_GROUP
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_STATUS   S ON F.STATUS_SK   = S.STATUS_SK
JOIN DIM_BUSINESS B ON F.BUSINESS_SK = B.BUSINESS_SK
JOIN DIM_CITY     C ON F.CITY_SK     = C.CITY_SK
WHERE S.STATUS_GROUP = 'Inactive'
ORDER BY C.CITY_NAME, B.LEGAL_NAME;



-- Q9: TOP 10 ORGANIZATIONS WITH HIGHEST FRANCHISE OWNERSHIPS BY CITY
-- Relations: FACT → DIM_BUSINESS, FACT → DIM_CITY
--            (FRANCHISE_PROXY is on FACT table)

SELECT *
FROM (
    SELECT
        C.CITY_NAME,
        B.LEGAL_NAME,
        MAX(F.FRANCHISE_PROXY) AS FRANCHISE_LOCATION_COUNT,
        ROW_NUMBER() OVER (
            PARTITION BY C.CITY_NAME
            ORDER BY MAX(F.FRANCHISE_PROXY) DESC
        ) AS RNK
    FROM FACT_BUSINESS_LICENSE F
    JOIN DIM_BUSINESS B ON F.BUSINESS_SK = B.BUSINESS_SK
    JOIN DIM_CITY     C ON F.CITY_SK     = C.CITY_SK
    GROUP BY C.CITY_NAME, B.LEGAL_NAME
) RANKED
WHERE RNK <= 10
ORDER BY CITY_NAME, RNK;



-- Q10: DISTRIBUTION OF BUSINESSES BY YEARS SINCE LICENSE ISSUANCE
-- Relations: FACT → DIM_DATE (via ISSUE_DATE_SK)


SELECT
    (YEAR(CURRENT_DATE) - D.YEAR) AS YEARS_SINCE_ISSUANCE,
    COUNT(*) AS LICENSE_COUNT
FROM FACT_BUSINESS_LICENSE F
JOIN DIM_DATE D ON F.ISSUE_DATE_SK = D.DATE_SK
GROUP BY (YEAR(CURRENT_DATE) - D.YEAR)
ORDER BY YEARS_SINCE_ISSUANCE;

